fix regression with Excel12f
```
 Error: xlld.framework.Excel12f called with argument types (int, XLOPER12*) matches both:
..\AppData\Roaming\dub\packages\excel-d-0.2.12\excel-d\source\xlld\framework.d(115,5):     xlld.framework.Excel12f(int xlfn, XLOPER12* pxResult, XLOPER12*[] args...)
and:
..\AppData\Roaming\dub\packages\excel-d-0.2.12\excel-d\source\xlld\framework.d(119,5):     xlld.framework.Excel12f(int xlfn, XLOPER12* result, XLOPER12[] args...)
```